version: "3.8"

services:
  pifrans-sonarqube:
    image: sonarqube:9.9.3-community
    container_name: pifrans-sonarqube
    hostname: pifrans-sonarqube
    depends_on:
      - pifrans-postgres-sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonar-network
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://pifrans-postgres-sonarqube:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - ./data/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/logs:/opt/sonarqube/logs
      - ./data/sonarqube/temp:/opt/sonarqube/temp

  pifrans-postgres-sonarqube:
    image: postgres:16.1
    container_name: pifrans-postgres-sonarqube
    hostname: pifrans-postgres-sonarqube
    networks:
      - sonar-network
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5444:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data


networks:
  sonar-network:
    driver: bridge


